# Generated by Django 5.1.6 on 2025-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.PositiveIntegerField(help_text='Estimated delivery time in days'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
