# Generated by Django 5.1.6 on 2025-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_product_supplier_product_suppliers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.IntegerField(help_text='Estimated delivery time in days'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
